version: 2.1

job_configuration: &job_configuration
  docker:
    - image: gableroux/dotnet-mono-monogame:latest
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install Dependencies
        command: chmod +x .circleci/build.sh && .circleci/build.sh
    - persist_to_workspace:
        root: ~/repo
        paths:
          - artifacts/

environment:
  PROJECT_NAME: NOBOIShooter
  MONOGAME_CONTENT_VERSION: 3.6

jobs:
  windows:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'win-x64'
      # Make sure your project targets .NET Core 2.2
      BUILD_FRAMEWORK: netcoreapp2.2
  linux:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'linux-x64'
      # Make sure your project targets .NET Core 2.2
      BUILD_FRAMEWORK: netcoreapp2.2
  macos:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'osx-x64'
      # Make sure your project targets .NET Core 2.2
      BUILD_FRAMEWORK: netcoreapp2.2

workflows:
  version: 2
  workflow:
    jobs:
      - windows
      - linux
      - macos
