version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      
    working_directory: ~/project
    
    steps:
      - checkout

      # Install MonoGame SDK on Windows
      - run:
          name: Install MonoGame SDK on Windows
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" && "$CIRCLE_OS" == "windows" ]]; then
              curl -L -o MonoGameSetup.exe https://github.com/MonoGame/MonoGame/releases/download/v3.6/MonoGameSetup.exe
              ./MonoGameSetup.exe /S
            fi

      # Build on Windows
      - run:
          name: Build on Windows
          command: msbuild NOBOIShooter.sln /p:Configuration=Release

      # Build on MacOS
      - run:
          name: Build on MacOS
          command: msbuild NOBOIShooter.sln /p:Configuration=Release

      # Build on Android
      - run:
          name: Build on Android
          command: msbuild NOBOIShooter.sln /p:Configuration=Release /t:Build /p:Platform=Android

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
