version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1  # Use a .NET Core SDK image

    working_directory: ~/repo

    steps:
      - checkout

      # Windows Build
      - run:
          name: Build on Windows
          command: |
            # Install MonoGame prerequisites for Windows
            choco install -y monogame
            # Your build command for Windows
            msbuild YourProject.sln /p:Configuration=Release /p:Platform=AnyCPU

      # MacOS Build
      - run:
          name: Build on MacOS
          command: |
            # Install MonoGame prerequisites for MacOS
            brew install mono
            brew install monogame
            # Your build command for MacOS
            msbuild YourProject.sln /p:Configuration=Release /p:Platform=AnyCPU

      # Android Build
      - run:
          name: Build on Android
          command: |
            # Install MonoGame prerequisites for Android
            # Include any additional Android setup commands
            # Your build command for Android
            msbuild YourAndroidProject.sln /p:Configuration=Release /p:Platform=AnyCPU

# Add more steps if necessary, such as running tests, deploying artifacts, etc.
