version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/powershell

    steps:
      - checkout

      # Install MonoGame SDK on Windows
      - run:
          name: Install MonoGame SDK on Windows
          command: |
            Invoke-WebRequest -Uri "https://github.com/MonoGame/MonoGame/releases/download/v3.6/MonoGameSetup.exe" -OutFile "MonoGameSetup.exe"
            Start-Process -Wait -FilePath "MonoGameSetup.exe" -ArgumentList "/S"

      # Build MonoGame for Windows
      - run:
          name: Build MonoGame for Windows
          command: dotnet publish NOBOIShooter.sln -c Release -r win-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained

      - persist_to_workspace:
          root: ./bin/Release/netcoreapp3.1/win-x64
          paths:
            - '**/*'

  build_macos:
    macos:
      xcode: 12.0.0

    steps:
      - checkout

      # Install MonoGame SDK on MacOS
      - run:
          name: Install MonoGame SDK on MacOS
          command: |
            curl -O -L "https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGame.pkg"
            sudo installer -pkg MonoGame.pkg -target /

      # Build MonoGame for MacOS
      - run:
          name: Build MonoGame for MacOS
          command: dotnet publish NOBOIShooter.sln -c Release -r osx-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained

      - persist_to_workspace:
          root: ./bin/Release/netcoreapp3.1/osx-x64
          paths:
            - '**/*'

  build_android:
    docker:
      - image: circleci/android:api-30

    steps:
      - checkout

      # Install MonoGame SDK on Android
      - run:
          name: Install MonoGame SDK on Android
          command: |
            curl -O -L "https://github.com/MonoGame/MonoGame/releases/download/v3.6/MonoGameSetup.exe"
            chmod +x MonoGameSetup.exe
            ./MonoGameSetup.exe /S

      # Build MonoGame for Android
      - run:
          name: Build MonoGame for Android
          command: dotnet publish NOBOIShooter.sln -c Release -r android -p:AndroidSdkDirectory=/usr/local/android-sdk

      - persist_to_workspace:
          root: ./bin/Release/netcoreapp3.1/android
          paths:
            - '**/*'

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_macos:
          requires:
            - build
      - build_android:
          requires:
            - build
